cycle_ids_AcCoA =   {{'CBB',0.5,'GAPtoOAA',0.5,'C3to2C2(4HB)(T)',0.5,'-PyrC',-0.5},...
                    {'CBB',0.55,'Photorespiration',0.05,'GAPtoOAA',0.5,'C3to2C2(4HB)(T)',0.5,'-PyrC',-0.5},...
                    {'CBB',1,'GAPtoOAA',1,'PyrKin',1,'PEPCarb',1,'PyrDehCompl',1},...
                    {'GED',0.5,'GAPtoOAA',0.5,'C3to2C2(4HB)(T)',0.5,'-PyrC',-0.5},...
                    {'GED',1,'GAPtoOAA',1,'PyrKin',1,'PEPCarb',1,'PyrDehCompl',1},...
                    {'HB/HP-Cren',1},...
                    {'HB/HP-Thaum',1},...
                    {'HP-bicycle',0.5,'C3to2C2(4HB)(T)',0.5},...
                    {'Serine',1},...
                    {'Serine(w/o SHMT)',1},...
                    {'RuMP',0.5,'MDH(NAD)',1.5,'GAPtoOAA',0.5,'C3to2C2(4HB)(T)',0.5,'-PyrC',-0.5},...
                    {'RuMP',0.5,'MDH(PQQ)',1.5,'GAPtoOAA',0.5,'C3to2C2(4HB)(T)',0.5,'-PyrC',-0.5},...
                    {'RuMP(Formate/THF)',0.5,'GAPtoOAA',0.5,'C3to2C2(4HB)(T)',0.5,'-PyrC',-0.5},...
                    {'rCCC',1},...
                    {'CETCH',1,'b-OH-AspCycle',0.5,'C3to2C2(4HB)(T)',0.5,'-PyrC',-0.5},...
                    {'CETCH',1,'b-OH-AspCycle',0.5,'MCG-like-cycle',0.5},...
                    {'CETCH',1,'GlyoxToGAP(GCL/GDH)',0.5,'GAPtoOAA',0.5,'C3to2C2(4HB)(T)',0.5,'-PyrC',-0.5},...
                    {'CETCH',1,'GlyoxToGAP(GCL/GDH)',0.5,'GAPtoOAA',0.5,'MCG-like-cycle',0.5},...
                    {'CETCH',1,'RevGlyoxShunt',1},...
                    {'rGlyP',1,'PyrDehCompl',1},...
                    {'rGlyP(w/o SHMT)',1,'PyrDehCompl',1},...
                    {'2-HG-rTCA',1,'SucFoCoA',1}};
                
cycle_ids_AcCoA_Formate =   {{'CBB',0.5,'GAPtoOAA',0.5,'C3to2C2(4HB)(T)',0.5,'-PyrC',-0.5,'FDH',4},...
                            {'CBB',0.55,'Photorespiration',0.05,'GAPtoOAA',0.5,'C3to2C2(4HB)(T)',0.5,'-PyrC',-0.5,'FDH',4.8},...
                            {'CBB',1,'GAPtoOAA',1,'PyrKin',1,'PEPCarb',1,'PyrDehCompl',1,'FDH',4},...
                            {'GED',0.5,'GAPtoOAA',0.5,'C3to2C2(4HB)(T)',0.5,'-PyrC',-0.5,'FDH',4},...
                            {'GED',1,'GAPtoOAA',1,'PyrKin',1,'PEPCarb',1,'PyrDehCompl',1,'FDH',4},...
                            {'HB/HP-Cren',1,'FDH',4},...
                            {'HB/HP-Thaum',1,'FDH',4},...
                            {'HP-bicycle',0.5,'C3to2C2(4HB)(T)',0.5,'FDH',4},...
                            {'Serine',1,'FDH',3},...
                            {'Serine(w/o SHMT)',1,'FDH',4},...
                            {'RuMP(Formate/THF)',0.5,'GAPtoOAA',0.5,'C3to2C2(4HB)(T)',0.5,'-PyrC',-0.5,'FDH',0.5},...
                            {'rCCC',1,'FDH',4},...
                            {'CETCH',1,'b-OH-AspCycle',0.5,'C3to2C2(4HB)(T)',0.5,'-PyrC',-0.5,'FDH',4},...
                            {'CETCH',1,'b-OH-AspCycle',0.5,'MCG-like-cycle',0.5,'FDH',4},...
                            {'CETCH',1,'GlyoxToGAP(GCL/GDH)',0.5,'GAPtoOAA',0.5,'C3to2C2(4HB)(T)',0.5,'-PyrC',-0.5,'FDH',4},...
                            {'CETCH',1,'GlyoxToGAP(GCL/GDH)',0.5,'GAPtoOAA',0.5,'MCG-like-cycle',0.5,'FDH',4},...
                            {'CETCH',1,'RevGlyoxShunt',1,'FDH',4},...
                            {'rGlyP',1,'PyrDehCompl',1,'FDH',2},...
                            {'rGlyP(w/o SHMT)',1,'PyrDehCompl',1,'FDH',2},...
                            {'2-HG-rTCA',1,'SucFoCoA',1,'FDH',3}};
                        
cycle_ids_AcCoA_H2 =   {{'CBB',0.5,'GAPtoOAA',0.5,'C3to2C2(4HB)(T)',0.5,'-PyrC',-0.5,'H2ase',4},...
                            {'CBB',0.55,'Photorespiration',0.05,'GAPtoOAA',0.5,'C3to2C2(4HB)(T)',0.5,'-PyrC',-0.5,'H2ase',4.8},...
                            {'CBB',1,'GAPtoOAA',1,'PyrKin',1,'PEPCarb',1,'PyrDehCompl',1,'H2ase',4},...
                            {'GED',0.5,'GAPtoOAA',0.5,'C3to2C2(4HB)(T)',0.5,'-PyrC',-0.5,'H2ase',4},...
                            {'GED',1,'GAPtoOAA',1,'PyrKin',1,'PEPCarb',1,'PyrDehCompl',1,'H2ase',4},...
                            {'HB/HP-Cren',1,'H2ase',4},...
                            {'HB/HP-Thaum',1,'H2ase',4},...
                            {'HP-bicycle',0.5,'C3to2C2(4HB)(T)',0.5,'H2ase',4},...
                            {'Serine',1,'FDH(red)',1,'H2ase',4},...
                            {'Serine(w/o SHMT)',1,'FDH(red)',1,'H2ase',4},...
                            {'RuMP(Formate/THF)',0.5,'GAPtoOAA',0.5,'C3to2C2(4HB)(T)',0.5,'-PyrC',-0.5,'FDH(red)',1.5,'H2ase',4},...
                            {'rCCC',1,'H2ase',4},...
                            {'CETCH',1,'b-OH-AspCycle',0.5,'C3to2C2(4HB)(T)',0.5,'-PyrC',-0.5,'H2ase',4},...
                            {'CETCH',1,'b-OH-AspCycle',0.5,'MCG-like-cycle',0.5,'H2ase',4},...
                            {'CETCH',1,'GlyoxToGAP(GCL/GDH)',0.5,'GAPtoOAA',0.5,'C3to2C2(4HB)(T)',0.5,'-PyrC',-0.5,'H2ase',4},...
                            {'CETCH',1,'GlyoxToGAP(GCL/GDH)',0.5,'GAPtoOAA',0.5,'MCG-like-cycle',0.5,'H2ase',4},...
                            {'CETCH',1,'RevGlyoxShunt',1,'H2ase',4},...
                            {'rGlyP',1,'PyrDehCompl',1,'FDH(red)',2,'H2ase',4},...
                            {'rGlyP(w/o SHMT)',1,'PyrDehCompl',1,'FDH(red)',2,'H2ase',4},...
                            {'2-HG-rTCA',1,'SucFoCoA',1,'FDH(red)',1,'H2ase',4}};
                        
cycle_ids_AcCoA_MeOH =      {{'CBB',0.5,'GAPtoOAA',0.5,'C3to2C2(4HB)(T)',0.5,'-PyrC',-0.5,'MDH(PQQ)',2,'FALDH',2,'FDH',2},...
                            {'CBB',0.55,'Photorespiration',0.05,'GAPtoOAA',0.5,'C3to2C2(4HB)(T)',0.5,'-PyrC',-0.5,'MDH(PQQ)',2,'FALDH',2,'FDH',2},...
                            {'CBB',1,'GAPtoOAA',1,'PyrKin',1,'PEPCarb',1,'PyrDehCompl',1,'MDH(PQQ)',2,'FALDH',2,'FDH',2},...
                            {'GED',0.5,'GAPtoOAA',0.5,'C3to2C2(4HB)(T)',0.5,'-PyrC',-0.5,'MDH(PQQ)',2,'FALDH',2,'FDH',2},...
                            {'GED',1,'GAPtoOAA',1,'PyrKin',1,'PEPCarb',1,'PyrDehCompl',1,'MDH(PQQ)',2,'FALDH',2,'FDH',2},...
                            {'HB/HP-Cren',1,'MDH(PQQ)',2,'FALDH',2,'FDH',2},...
                            {'HB/HP-Thaum',1,'MDH(PQQ)',2,'FALDH',2,'FDH',2},...
                            {'HP-bicycle',0.5,'C3to2C2(4HB)(T)',0.5,'MDH(PQQ)',2,'FALDH',2,'FDH',2},...
                            {'Serine',1,'MDH(PQQ)',2,'FALDH',2,'FDH',1},...
                            {'Serine',1,'MDH(NAD)',1.33,'FALDH',1.33,'FDH',0.33},...
                            {'Serine(w/o SHMT)',1,'MDH(PQQ)',2,'FALDH',2,'FDH',2},...
                            {'Serine(w/o SHMT)',1,'MDH(NAD)',1.33,'FALDH',1.33,'FDH',0.33},...
                            {'RuMP',0.5,'GAPtoOAA',0.5,'C3to2C2(4HB)(T)',0.5,'-PyrC',-0.5,'MDH(PQQ)',2,'FALDH',0.5,'FDH',0.5},...
                            {'RuMP',0.5,'GAPtoOAA',0.5,'C3to2C2(4HB)(T)',0.5,'-PyrC',-0.5,'MDH(NAD)',1.5},...
                            {'rCCC',1,'MDH(PQQ)',2,'FALDH',2,'FDH',2},...
                            {'CETCH',1,'b-OH-AspCycle',0.5,'C3to2C2(4HB)(T)',0.5,'-PyrC',-0.5,'MDH(PQQ)',2,'FALDH',2,'FDH',2},...
                            {'CETCH',1,'b-OH-AspCycle',0.5,'MCG-like-cycle',0.5,'MDH(PQQ)',2,'FALDH',2,'FDH',2},...
                            {'CETCH',1,'GlyoxToGAP(GCL/GDH)',0.5,'GAPtoOAA',0.5,'C3to2C2(4HB)(T)',0.5,'-PyrC',-0.5,'MDH(PQQ)',2,'FALDH',2,'FDH',2},...
                            {'CETCH',1,'GlyoxToGAP(GCL/GDH)',0.5,'GAPtoOAA',0.5,'MCG-like-cycle',0.5,'MDH(PQQ)',2,'FALDH',2,'FDH',2},...
                            {'CETCH',1,'RevGlyoxShunt',1,'MDH(PQQ)',2,'FALDH',2,'FDH',2},...
                            {'rGlyP',1,'PyrDehCompl',1,'MDH(PQQ)',2,'FALDH',2},...
                            {'rGlyP',1,'PyrDehCompl',1,'MDH(PQQ)',2,'FALDH',2},...
                            {'rGlyP',0.5,'C3to2C2(4HB)(T)',0.5,'MDH(PQQ)',2,'FALDH',2,'FDH',1},...
                            {'rGlyP',0.5,'C3to2C2(4HB)(T)',0.5,'MDH(NAD)',1.33,'FALDH',1.33,'FDH',0.33},...
                            {'rGlyP(w/o SHMT)',1,'PyrDehCompl',1,'MDH(PQQ)',2,'FALDH',2},...
                            {'rGlyP(w/o SHMT)',1,'PyrDehCompl',1,'MDH(NAD)',2,'FALDH',2},...
                            {'rGlyP(w/o SHMT)',0.5,'C3to2C2(4HB)(T)',0.5,'MDH(PQQ)',2,'FALDH',2,'FDH',1},...
                            {'rGlyP(w/o SHMT)',0.5,'C3to2C2(4HB)(T)',0.5,'MDH(NAD)',1.33,'FALDH',1.33,'FDH',0.33},...
                            {'2-HG-rTCA',1,'SucFoCoA',1,'MDH(PQQ)',2,'FALDH',2,'FDH',1},...
                            {'2-HG-rTCA',1,'FCL',1,'MDH(PQQ)',2,'FALDH',1,'FDH',1},...
                            {'2-HG-rTCA',1,'SucFoCoA',1,'MDH(NAD)',1.33,'FALDH',1.33,'FDH',0.33}};
                
%cycle_ids_AcCoA =   {{'rCCC',1}};

cycle_ids_Oxac =    {{'CBB',1,'GAPtoOAA',1},...
                    {'CBB(Photorespiration)',1.1,'Photorespiration',0.1,'GAPtoOAA',1},...
                    {'CBB(PTS)',1,'GAPtoOAA',1},...
                    {'HB/HP-Cren',1,'rCC-AcCoAtoPyr',1,'PyrC',1},...
                    {'HB/HP-Cren',1,'AcCoAtoOAA(HP)(AMP)',1},...
                    {'HB/HP-Thaum',1,'rCC-AcCoAtoPyr',1,'PyrC',1},...
                    {'HB/HP-Thaum',1,'AcCoAtoOAA(HP)(ADP)',1},...
                    {'HP-bicycle',1,'PyrC',1},...
                    {'HP-bicycle(ADP)',1,'PyrC',1},...
                    {'HP-bicycle(glyox)',2,'b-OH-AspCycle',1},...
                    {'HP-bicycle(glyox)(ADP)',2,'b-OH-AspCycle',1},...
                    {'Serine-Cycle(w/o SHMT)',1,'EtMalOAAGlyox',0.5,'GlyoxToOAA(Ser)',0.5},...
                    {'Serine-Cycle',1,'EtMalOAAGlyox',0.5,'GlyoxToOAA(Ser)',0.5},...
                    {'RuMP',1,'GAPtoOAA',1},...
                    {'RuMP(Formate/THF)',1,'GAPtoOAA',1},...
                    {'rCCC',1,'rCC-AcCoAtoPyr',1,'PyrC',1},...
                    {'CETCH',2,'b-OH-AspCycle',1},...
                    {'CETCH',1,'GlyoxToOAA-HPbicycle(AMP)',1},...
                    {'rGlyP',1,'PyrC',1},...
                    {'rGlyP(w/o SHMT)',1,'PyrC',1},...
                    {'2-HG-rTCA',1,'rCC-AcCoAtoPyr',1,'PyrC',1}};

cycle_ids_GAP =     {{'CBB',1},...
                    {'CBB(Photorespiration)',1.1,'Photorespiration',0.1},...
                    {'CBB(PTS)',1},...
                    {'GED',1},...
                    {'HB/HP-Cren',1,'rCC-AcCoAtoPyr',1,'PyrC',1,'OAAtoGAP',1},...
                    {'HB/HP-Cren',1,'AcCoAtoOAA(HP)(AMP)',1,'OAAtoGAP',1},...
                    {'HB/HP-Thaum',1,'rCC-AcCoAtoPyr',1,'PyrC',1,'OAAtoGAP',1},...
                    {'HB/HP-Thaum',1,'AcCoAtoOAA(HP)(ADP)',1,'OAAtoGAP',1},...
                    {'HP-bicycle',1,'PyrC',1,'OAAtoGAP',1},...
                    {'HP-bicycle(ADP)',1,'PyrC',1,'OAAtoGAP',1},...
                    {'HP-bicycle(glyox)',2,'b-OH-AspCycle',1,'OAAtoGAP',1},...
                    {'HP-bicycle(glyox)(ADP)',2,'b-OH-AspCycle',1,'OAAtoGAP',1},...
                    {'Serine',1,'EtMalOAAGlyox',0.5,'GlyoxToOAA(Ser)',0.5,'OAAtoGAP',1},...
                    {'Serine(w/o SHMT)',1,'EtMalOAAGlyox',0.5,'GlyoxToOAA(Ser)',0.5,'OAAtoGAP',1},...
                    {'RuMP',1,'MDH(NAD)',3},...
                    {'RuMP(ED)',1,'MDH(NAD)',3},...
                    {'RuMP',1,'MDH(PQQ)',3},...
                    {'RuMP(ED)',1,'MDH(PQQ)',3},...
                    {'RuMP(Formate/THF)',1,'FDH',3},...
                    {'rCCC',1,'rCC-AcCoAtoPyr',1,'PyrC',1,'OAAtoGAP',1},...
                    {'MOG(PyrC)',2,'b-OH-AspCycle',1,'OAAtoGAP',1},...
                    {'CETCH',2,'b-OH-AspCycle',1,'OAAtoGAP',1},...
                    {'CETCH',1,'GlyoxToOAA-HPbicycle(AMP)',1,'OAAtoGAP',1},...
                    {'CETCH',2,'GlyoxToGAP(GCL/GDH)',1},...
                    {'rGlyP',1,'PyrC',1,'OAAtoGAP',1},...
                    {'rGlyP(w/o SHMT)',1,'PyrC',1,'OAAtoGAP',1},...
                    {'2-HG-rTCA',1,'rCC-AcCoAtoPyr',1,'PyrC',1,'OAAtoGAP',1,'SucFoCoA',1}};

% cycle_ids_GAP =     {{'Serine-Cycle',1,'EtMalOAAGlyox',0.5,'GlyoxToOAA(Ser)',0.5,'OAAtoGAP',1,'FDH(red)',1.5},...
%                     {'Serine-Cycle(w/o SHMT)',1,'EtMalOAAGlyox',0.5,'GlyoxToOAA(Ser)',0.5,'OAAtoGAP',1,'FDH(red)',1.5}};

cycle_ids_GAP_Formate = {{'CBB',1,'FDH',6},...
                        {'CBB(PTS)',1,'FDH',6},...
                        {'CBB(Photorespiration)',1.1,'Photorespiration',0.1,'FDH',7.2},...
                        {'GED',1,'FDH',6},...
                        {'HB/HP-Cren',1,'rCC-AcCoAtoPyr',1,'PyrC',1,'OAAtoGAP',1,'FDH',6},...
                        {'HB/HP-Thaum',1,'rCC-AcCoAtoPyr',1,'PyrC',1,'OAAtoGAP',1,'FDH',6},...
                        {'HB/HP-Thaum',1,'AcCoAtoOAA(HP)(ADP)',1,'OAAtoGAP',1,'FDH',6},...
                        {'HP-bicycle',1,'PyrC',1,'OAAtoGAP',1,'FDH',6},...
                        {'HP-bicycle(ADP)',1,'PyrC',1,'OAAtoGAP',1,'FDH',6},...
                        {'HP-bicycle(glyox)',2,'b-OH-AspCycle',1,'OAAtoGAP',1,'FDH',6},...
                        {'HP-bicycle(glyox)(ADP)',2,'b-OH-AspCycle',1,'OAAtoGAP',1,'FDH',6},...
                        {'Serine',1,'FDH',4.5,'EtMalOAAGlyox',0.5,'GlyoxToOAA(Ser)',0.5,'OAAtoGAP',1},...
                        {'Serine(w/o SHMT)',1,'FDH',4.5,'EtMalOAAGlyox',0.5,'GlyoxToOAA(Ser)',0.5,'OAAtoGAP',1},...
                        {'RuMP(Formate/THF)',1,'FDH',3},...
                        {'rCCC',1,'rCC-AcCoAtoPyr',1,'PyrC',1,'OAAtoGAP',1,'FDH',6},...
                        {'MOG(PyrC)',2,'b-OH-AspCycle',1,'OAAtoGAP',1,'FDH',6},...
                        {'CETCH',2,'b-OH-AspCycle',1,'OAAtoGAP',1,'FDH',6},...
                        {'CETCH',1,'GlyoxToOAA-HPbicycle(AMP)',1,'OAAtoGAP',1,'FDH',6},...
                        {'CETCH',2,'GlyoxToGAP(GCL/GDH)',1,'FDH',6},...
                        {'rGlyP',1,'FDH',4,'PyrC',1,'OAAtoGAP',1},...
                        {'rGlyP(w/o SHMT)',1,'FDH',4,'PyrC',1,'OAAtoGAP',1},...
                        {'2-HG-rTCA',1,'FDH',5,'rCC-AcCoAtoPyr',1,'PyrC',1,'OAAtoGAP',1,'SucFoCoA',1}};


cycle_ids_GAP_MeOH = {{'CBB',1,'MDH(NAD)',2,'FALDH',2,'FDH',2},...
                     {'CBB',1,'MDH(PQQ)',3,'FALDH',3,'FDH',3},...
                     {'CBB(Photorespiration)',1.1,'Photorespiration',0.1,'MDH(PQQ)',3.3,'FALDH',3.3,'FDH',3.3},...
                     {'GED',1,'MDH(NAD)',2,'FALDH',2,'FDH',2},...
                     {'GED',1,'MDH(PQQ)',3,'FALDH',3,'FDH',3},...
                     {'HB/HP-Cren',1,'rCC-AcCoAtoPyr',1,'PyrC',1,'OAAtoGAP',1,'MDH(PQQ)',3,'FALDH',3,'FDH',3},...
                     {'HB/HP-Cren',1,'AcCoAtoOAA(HP)(AMP)',1,'OAAtoGAP',1,'MDH(PQQ)',3,'FALDH',3,'FDH',3},...
                     {'HB/HP-Cren',1,'rCC-AcCoAtoPyr',1,'PyrC',1,'OAAtoGAP',1,'MDH(NAD)',2,'FALDH',2,'FDH',2},...
                     {'HB/HP-Cren',1,'AcCoAtoOAA(HP)(AMP)',1,'OAAtoGAP',1,'MDH(NAD)',2,'FALDH',2,'FDH',2},...
                     {'HB/HP-Thaum',1,'rCC-AcCoAtoPyr',1,'PyrC',1,'OAAtoGAP',1,'MDH(PQQ)',3,'FALDH',3,'FDH',3},...
                     {'HB/HP-Thaum',1,'AcCoAtoOAA(HP)(ADP)',1,'OAAtoGAP',1,'MDH(PQQ)',3,'FALDH',3,'FDH',3},...
                     {'HP-bicycle',1,'PyrC',1,'OAAtoGAP',1,'MDH(PQQ)',3,'FALDH',3,'FDH',3},...
                     {'HP-bicycle(ADP)',1,'PyrC',1,'OAAtoGAP',1,'MDH(PQQ)',3,'FALDH',3,'FDH',3},...
                     {'HP-bicycle(glyox)',2,'b-OH-AspCycle',1,'OAAtoGAP',1,'MDH(PQQ)',3,'FALDH',3,'FDH',3},...
                     {'HP-bicycle(glyox)(ADP)',2,'b-OH-AspCycle',1,'OAAtoGAP',1,'MDH(PQQ)',3,'FALDH',3,'FDH',3},...
                     {'HP-bicycle',1,'PyrC',1,'OAAtoGAP',1,'MDH(NAD)',2,'FALDH',2,'FDH',2},...
                     {'HP-bicycle(ADP)',1,'PyrC',1,'OAAtoGAP',1,'MDH(NAD)',2,'FALDH',2,'FDH',2},...
                     {'HP-bicycle(glyox)',2,'b-OH-AspCycle',1,'OAAtoGAP',1,'MDH(NAD)',2,'FALDH',2,'FDH',2},...
                     {'HP-bicycle(glyox)(ADP)',2,'b-OH-AspCycle',1,'OAAtoGAP',1,'MDH(NAD)',2,'FALDH',2,'FDH',2},...
                     {'Serine',1,'MDH(PQQ)',1.5,'FALDH',1.5,'EtMalOAAGlyox',0.5,'GlyoxToOAA(Ser)',0.5,'OAAtoGAP',1},...
                     {'Serine(w/o SHMT)',1,'MDH(PQQ)',1.5,'FALDH',1.5,'EtMalOAAGlyox',0.5,'GlyoxToOAA(Ser)',0.5,'OAAtoGAP',1},...
                     {'RuMP',1,'MDH(NAD)',3},{'RuMP(ED)',1,'MDH(NAD)',3},...
                     {'RuMP',1,'MDH(PQQ)',3},{'RuMP(ED)',1,'MDH(PQQ)',3},...
                     {'rCCC',1,'rCC-AcCoAtoPyr',1,'PyrC',1,'OAAtoGAP',1,'MDH(NAD)',2,'FALDH',2,'FDH',2},...
                     {'rCCC',1,'rCC-AcCoAtoPyr',1,'PyrC',1,'OAAtoGAP',1,'MDH(PQQ)',3,'FALDH',3,'FDH',3},...
                     {'CETCH',1,'GlyoxToOAA-HPbicycle(AMP)',1,'OAAtoGAP',1,'MDH(NAD)',2,'FALDH',2,'FDH',2},...
                     {'CETCH',2,'GlyoxToGAP(GCL/GDH)',1,'MDH(NAD)',2,'FALDH',2,'FDH',2},...
                     {'CETCH',2,'b-OH-AspCycle',1,'OAAtoGAP',1,'MDH(PQQ)',3,'FALDH',3,'FDH',3},...
                     {'CETCH',1,'GlyoxToOAA-HPbicycle(AMP)',1,'OAAtoGAP',1,'MDH(PQQ)',3,'FALDH',3,'FDH',3},...
                     {'CETCH',2,'GlyoxToGAP(GCL/GDH)',1,'MDH(PQQ)',3,'FALDH',3,'FDH',3},...
                     {'MOG(PyrC)',2,'b-OH-AspCycle',1,'OAAtoGAP',1,'MDH(NAD)',2,'FALDH',2,'FDH',2},...
                     {'MOG(PyrC)',2,'b-OH-AspCycle',1,'OAAtoGAP',1,'MDH(PQQ)',3,'FALDH',3,'FDH',3},...
                     {'rGlyP',1,'MDH(NAD)',2,'FALDH',2,'PyrC',1,'OAAtoGAP',1},...
                     {'rGlyP(w/o SHMT)',1,'MDH(NAD)',2,'FALDH',2,'PyrC',1,'OAAtoGAP',1},...
                     {'rGlyP',1,'MDH(PQQ)',3,'FALDH',3,'FDH',1,'PyrC',1,'OAAtoGAP',1},...
                     {'rGlyP(w/o SHMT)',1,'MDH(PQQ)',3,'FALDH',3,'FDH',1,'PyrC',1,'OAAtoGAP',1},...
                     {'2-HG-rTCA',1,'MDH(PQQ)',3,'FCL',1,'FALDH',2,'FDH',2,'rCC-AcCoAtoPyr',1,'PyrC',1,'OAAtoGAP',1}};
                 
cycle_ids_GAP_H2 =      {{'CBB',1,'H2ase',6},...
                        {'CBB(PTS)',1,'H2ase',6},...
                        {'CBB(Photorespiration)',1.1,'Photorespiration',0.1,'H2ase',6.6},...
                        {'GED',1,'H2ase',6},...
                        {'HB/HP-Cren',1,'rCC-AcCoAtoPyr',1,'PyrC',1,'OAAtoGAP',1,'H2ase',6},...
                        {'HB/HP-Thaum',1,'rCC-AcCoAtoPyr',1,'PyrC',1,'OAAtoGAP',1,'H2ase',6},...
                        {'HB/HP-Thaum',1,'AcCoAtoOAA(HP)(ADP)',1,'OAAtoGAP',1,'H2ase',6},...
                        {'HP-bicycle',1,'PyrC',1,'OAAtoGAP',1,'H2ase',6},...
                        {'HP-bicycle(ADP)',1,'PyrC',1,'OAAtoGAP',1,'H2ase',6},...
                        {'HP-bicycle(glyox)',2,'b-OH-AspCycle',1,'OAAtoGAP',1,'H2ase',6},...
                        {'HP-bicycle(glyox)(ADP)',2,'b-OH-AspCycle',1,'OAAtoGAP',1,'H2ase',6},...
                        {'Serine',1,'FDH(red)',1.5,'EtMalOAAGlyox',0.5,'GlyoxToOAA(Ser)',0.5,'OAAtoGAP',1,'H2ase',6},...
                        {'Serine(w/o SHMT)',1,'FDH(red)',1.5,'EtMalOAAGlyox',0.5,'GlyoxToOAA(Ser)',0.5,'OAAtoGAP',1,'H2ase',6},...
                        {'RuMP(Formate/THF)',1,'FDH(red)',3,'H2ase',6},...
                        {'rCCC',1,'rCC-AcCoAtoPyr',1,'PyrC',1,'OAAtoGAP',1,'H2ase',6},...
                        {'MOG(PyrC)',2,'b-OH-AspCycle',1,'OAAtoGAP',1,'H2ase',6},...
                        {'CETCH',2,'b-OH-AspCycle',1,'OAAtoGAP',1,'H2ase',6},...
                        {'CETCH',1,'GlyoxToOAA-HPbicycle(AMP)',1,'OAAtoGAP',1,'H2ase',6},...
                        {'CETCH',2,'GlyoxToGAP(GCL/GDH)',1,'H2ase',6},...
                        {'rGlyP',1,'FDH(red)',2,'H2ase',6,'PyrC',1,'OAAtoGAP',1},...
                        {'rGlyP(w/o SHMT)',1,'FDH(red)',2,'H2ase',6,'PyrC',1,'OAAtoGAP',1},...
                        {'2-HG-rTCA',1,'FDH(red)',1,'H2ase',6,'rCC-AcCoAtoPyr',1,'PyrC',1,'OAAtoGAP',1,'SucFoCoA',1}};